name: flutter_pcm
description: "PCM Audio Player"
version: 0.0.1
homepage: "https://none"

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterPcmPluginCApi
      linux:
        pluginClass: FlutterPcmPlugin
      ios:
        pluginClass: FlutterPcmPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterPcmPlugin
        sharedDarwinSource: true

